services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - app-network
    volumes:
      - ./.env:/app/.env:ro
    develop:
      watch:
        - action: sync
          path: .
          target: /code

networks:
  app-network:
    driver: bridge
